# Can be used for Docker swarm to scale the project to be used with multiple machine in a swarm and with multiple replicas per node

version: '3.9'

services:
  urlshortener: 
    image: urlshortener/server
    restart: always
    networks: 
      urlshortenernetwork:
    deploy:
      replicas: ${URLSHORTENER_CORE_INSTANCES}
      placement:
        max_replicas_per_node: 1
    depends_on:
      - urlshortener-db
    environment:
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DIALECT: ${DB_DIALECT}
  urlshortener-db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    networks: 
      urlshortenernetwork:
    volumes:
     - type: tmpfs
       target: /dev/shm
       tmpfs:
         size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_NAME: ${DB_NAME:-urlshortener}
      POSTGRES_USER: ${DB_USERNAME:-urlshortener}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-urlshortener}
    ports:
      - 5432:5432
      
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
networks:
  urlshortenernetwork:
    name: urlshortenernetwork
