version: '3.9'

services:
  urlshortener-db:
    image: postgres
    restart: always
    networks: 
      munchposnetwork:
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    volumes:
     - type: tmpfs
       target: /dev/shm
       tmpfs:
         size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_NAME: urlshortener
      POSTGRES_USER: urlshortener
      POSTGRES_PASSWORD: urlshortener
    ports:
      - 5432:5432
      
  adminer:
    image: adminer
    restart: always
    networks: 
      munchposnetwork:
    ports:
      - 8080:8080

networks:
  munchposnetwork:
    name: munchposnetwork